### PR TITLE
Adding new code to match with recent changes in FluidSynth library

### LINKED ISSUE #73: Not working with fluidsynth 2
Hello and thanks for the great package!

I was getting: ImportError("Couldn't find the FluidSynth library.")

I think it was because I have fluidsynth 2 installed and mingus isn't yet compatible.

Things seem to work when I tweak pyfluidsynth by adding find_library("libfluidsynth-2") into the ctype.utils search...

### PR DESCRIPTION
**Pull request by PettaBoy**
These changes have been made in https://github.com/nwhitehead/pyfluidsynth/blob/master/fluidsynth.py repo as well. Reasons given there.

Closes #73

### CODE REVIEW

**Comment by edudobay** [comment]
Note: closes #73

**Comment by PettaBoy** [comment]
Might be either in your projects folder, or better, in the midi folder where FluidSynth bindings are installed?
I'll add code for the latter as well.

**Comment by PettaBoy** [comment]
Hey @edudobay, I've made few changes to fluidsynth since the day I've posted this. These changes make sure that mingus will work well with fluidsynth DLLs without us having to add it to path. But this will require us to create a new fluidsynth folder and ask people to put in the fluidsynth DLLs there, or we might have to do that ourselves. What do you think? Should I put it over here, or should I put it in a new PR?
Also tagging @bspaans into the discussion.

**Comment by edudobay** [comment]
Hi @PettaBoy! I think your proposal is a good default, and I added an environment variable to make this adjustable. I'm merging this!

**Comment by PettaBoy** [comment]
Thanks for this merge, @edudobay! The FluidSynth library problem should be fixed at last.
However, the FluidSynth library fix wasn't the only addition I wanted to make.
Ever since I opened this PR, more changes seem to have been added to the https://github.com/nwhitehead/pyfluidsynth/blob/master/fluidsynth.py repo wrt MIDI event analysis, file playing and external router support. It would have been better to add all of them at once - however this PR was closed before that.
Would you like me to open a new PR to add the rest of these changes?

**Comment by PettaBoy** [comment]
Btw, sorry for responding this late - I had some work to do.

**Pull request merged**
